### ISSUE TITLE
[Dart compiler issue] containsLocation is not working as expected as from original Java project

### ISSUE THREAD

**Issue by nicolascavallin** [KohlsAdrian/google_maps_utils#1]
First of all, thanks for your work because it is a good one.

The only function that I don't get to work is _containsLocation_, and its partner _containsLocationPoint_.

I tried different polygons and points inside, outside and at the border, even with and without geodesic, but in all cases I get false.

Maybe I'm implementing it badly, but I don't know.

I leave an example below:

`PolyUtils.containsLocation(LatLng(-31.623060136389135,-60.68669021129609), [LatLng(-31.624115,-60.688734),LatLng(-31.624115,-60.684657),LatLng(-31.621594,-60.686717),LatLng(-31.624115,-60.688734)], false)`

Its return **false**, but it should be true:

<img width="1467" alt="Captura de Pantalla 2020-02-12 a la(s) 06 31 57" src="https://user-images.githubusercontent.com/22961489/74321667-6fbc4f80-4d61-11ea-952c-92abd6e7e767.png">

Thanks.

**Comment by KohlsAdrian** [comment]
hi @nicolascav , thanks for your feedback, I am checking right know, just to know, are you using the last version?

**Comment by nicolascavallin** [comment]
Yes I am!
Thanks for your time.

**Comment by KohlsAdrian** [comment]
in the private method `intersects ` the calcs of the LatLng's are having precision values

for example: your LatLng point has 15 decimal places, and the polygon points are having 6 decimal places, for very small values lower than 0.0000 calc in `intersects return;` like the points are not closed, so impossible to say that the point is inside the polygon.

But in conclusion, your example has to be true, I think it's a compiler trick that I have to implement, but I am studying the case

**Comment by KohlsAdrian** [comment]
It's a compiler issue, it is confirmed, I copied the code from original Android Java project, and @nicolascav code has to be true

![image](https://user-images.githubusercontent.com/6604704/74345358-c5f2b800-4d8c-11ea-8e15-2f3a57c6e99b.png)

Working on a fix to dart compiler

**Comment by nicolascavallin** [comment]
Nice!

Thanks! :)

**Comment by KohlsAdrian** [comment]
value of PI in Java Math = 3.14159265358979323846
value of PI in Dart Math = 3.1415926535897932

Different values, different results

Trying custom pi from java, checking if I have to replace other math functions, like:
 - log
 - tan
 - pow
 - sin
 - etc...
