### ISSUE TITLE
problem with simplify

### ISSUE THREAD

**Issue by 0oL** [KohlsAdrian/google_maps_utils#2]
I use the  `PolyUtils.simplify`  ,If the incoming path list is a closed path ,an error will be reported.
This is wrong because poly uses the `remove` method instead of `removeAt` .

**Comment by KohlsAdrian** [comment]
Hi @0oL, thanks for using the package, can you post your example and error log so I can check?

**Comment by 0oL** [comment]
Hi @KohlsAdrian ,I deleted the log but I found the reason

**Comment by KohlsAdrian** [comment]
So, there is nothing?
