### ISSUE TITLE
[SOLVED] [1.3.0] Feature Request: LatLngBounds from a List<LatLng>

### ISSUE THREAD

**Issue by adam-ashored** [KohlsAdrian/google_maps_utils#5]
Kind of nutty (IMO) that google has left out the ability to simply extend a LatLngBounds to create a bounds (NE/SW combo) from a List<LatLng> (see https://stackoverflow.com/a/31029389/3182210) - it is such a basic requirement of Map UIs. 

Incorporating this functionality into a library instead of requiring the user to implement it themselves would be a pretty nice feature.

Not sure if I missed this capability in the docs, but it didn't jump out at me in an obvious way.

**Comment by KohlsAdrian** [comment]
Hi Adam, this functionality exists, but I replaced for native Dart objects

[See this file](https://github.com/KohlsAdrian/google_maps_utils/blob/master/lib/spherical_utils.dart)

You can see I made this GMULatLngBounds class, it contains two variables, northEast and southWest

They are the coordinates for what you want

Example:

northEast.x for Latitude
northEast.y for Longitude

**Comment by KohlsAdrian** [comment]
Hi Adam, thanks for using the plugin.

You have a good point. The plugin do not have this feature. I'll add this feature ASAP

**Comment by KohlsAdrian** [comment]
Adam, the feature is available as of [this commit](https://github.com/KohlsAdrian/google_maps_utils/commit/56d3e385fea02c61bdb4962efd269c12edafff06)

You wanna use "toBoundsFromPoints" from SphericalUtils class, that will solve your problem, I have used this snippet in a freelancer, so it was quick to add.

The package is already available, version 1.3.0
